### PR TITLE
[WIP] Simplify key generation

### PR DESCRIPTION
**Pull request by andrewosh**
`corestore-next` has been working with an internal `KeyManager` class that we don't need. The idea was originally to use an abstraction that wraps async signing, such that one could eventually offload that task to another device, but that's jumping the gun.

This PR removes that and simplifies the internals quite a bit as a result. It also exposes:
1.  A `createKeyPair` method that can be used to generate ED25519 keys (for both Hypercore and Hyperswarm).
2. A `primaryKey` option, if you want to load the primary key from elsewhere, or for reproducible key generation during testing. 

Needs docs.

__Note: This change completely breaks the storage format and the `name` -> `key` mapping, so it's super incompatible with earlier alpha releases of `corestore-next`__

### CODE REVIEW

**Comment by mafintosh** [comment]
Looks great! nice and simple

**Comment by Nazeh** [comment]
If only `NAMESPACE` could be customized, I would ditch my customized and simplified `KeyManager` and use this instead.

Love it anyway.

**Comment by mafintosh** [comment]
@Nazeh what was your usecase for that?

**Comment by Nazeh** [comment]
@mafintosh I needed to use the same KeyPair for both a Hyperswarm and Hypercore instance (solved by this PR), but I also wanted to be able to write specs for how to derive Slashtag Keypairs from a Bitcoin seed, and using `@hyperspace/key-manager` as the `NAMESPACE` would have been strange.

**Comment by Nazeh** [comment]
Would it make sense to name that option `application` and have it default to `corestore`... This way multiple applications can use the same storage, Corestore's resources, and even the same namespaces, and still have a separation between applications.

I understand that this can already be done using `namespace()` but at least this gives applications more control over the key derivation scheme.

**Comment by mafintosh** [comment]
Yea something like that is fine with me 👍

**Pull request merged**
